### ISSUE TITLE
Connection issues with gogohd

### ISSUE THREAD

**Issue by on-ii** [sdaqo/anipy-cli#107]
**Describe the bug**
anipy-cli fails to load any episodes.

**To Reproduce**

  1.  Start anipy-cli
  2. Search for and select an anime, then select an episode
  3. See error

**Expected behavior**
A mpv window opens and the anime starts playing.

**Info**
Name: anipy-cli
Version: 2.5.12
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /home/m3hr4b/.local/lib/python3.10/site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, kitsu.py-extended, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, pyyaml, requests, setuptools, tqdm
Required-by: 

**Platform**
 - OS: Manjaro 6.1.1-1
 - Maybe something else that is specific to your platform and may have impact on the bug

**Additional context**
error messege:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1e077a9f30>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gogohd.pro', port=443): Max retries exceeded with url: /streaming.php?id=MTkxOTY3&title=Lycoris+Recoil+Episode+11&typesub=SUB (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1e077a9f30>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m3hr4b/.local/bin/anipy-cli", line 8, in <module>
    sys.exit(main())
  File "/home/m3hr4b/.local/lib/python3.10/site-packages/anipy_cli/run_anipy_cli.py", line 8, in main
    cli.main()
  File "/home/m3hr4b/.local/lib/python3.10/site-packages/anipy_cli/cli.py", line 708, in main
    history_cli(args.quality, player)
  File "/home/m3hr4b/.local/lib/python3.10/site-packages/anipy_cli/cli.py", line 193, in history_cli
    url_class.stream_url()
  File "/home/m3hr4b/.local/lib/python3.10/site-packages/anipy_cli/url_handler.py", line 355, in stream_url
    data = self.aes_decrypt(self.get_data(), self.key).decode()
  File "/home/m3hr4b/.local/lib/python3.10/site-packages/anipy_cli/url_handler.py", line 338, in get_data
    r = self.session.get(self.entry.embed_url)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gogohd.pro', port=443): Max retries exceeded with url: /streaming.php?id=MTkxOTY3&title=Lycoris+Recoil+Episode+11&typesub=SUB (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1e077a9f30>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by sdaqo** [comment]
Can you post your config?

**Comment by XaaRii** [comment]
I can confirm, also does the same thing to me on my windows machine.
error: https://pastebin.com/2GhnTXBd
config file:
```
download_folder_path: "./downloads"
seasonals_dl_path: "./downloads/seasonals"
user_files_path: "~/anipy-cli/user_files"

# Url of the goganime website, only change if needed
gogoanime_url: "https://gogoanime.gg/"

# Supported Players are: mpv, vlc, syncplay, mpvnet
player_path: "mpv"

mpv_commandline_options:
  - "--fs"
  - "--cache"
  - "--keep-open=always"
  - "--keep-open-pause=no"
  - "--geometry=100%:0%"
  - "--autofit-larger=1366x768"

vlc_commandline_options: []

# Reuse the mpv window instead of closing and reopening. Default: False
reuse_mpv_window: True

ffmpeg_hls: False
download_name_format: "{show_name}_{episode_number}_{quality}.mp4"
download_remove_dub_from_folder_name: True

# Discord Presence: Default: False
dc_presence: True
```
I doubt it's a problem with configs, most likely some changes happened on gogoanime. I don't update anipy when I don't have to (of course if something like this happens I pull latest from git) and today when trying to watch a new episode i was greeted with this traceback.
I don't think there is much else to say.

**Comment by zack-ani** [comment]
Gogoanime is offline if you change the streaming.php url to gogohd.net/streaming.php?id 

it works just fine. temp fix for right now

**Comment by Quicksilver151** [comment]
whats streaming.php?

**Comment by Quicksilver151** [comment]
well....

either way, it looks like its working again. so probably best to close this

**Comment by on-ii** [comment]
looks like its working again. closing this issue
