### ISSUE TITLE
Dubs not available in search

### ISSUE THREAD

**Issue by voidxd** [sdaqo/anipy-cli#117]
Hello,

First of all, thank you very much for this tool. 
I've been using it for a month, and it has been working great, and I've been loving it. 

I'm using it on Ubuntu 22.04 with anipy-cli 2.7.3

I updated it 24-ish hours ago and when searching for dubbed anime none show up in search. Then I updated just now to 2.7.3 and the issue persists:

Examples:

- Searching for anime name and expecting to select the dubbed version:
   ![image](https://user-images.githubusercontent.com/58847957/219964248-d8495091-828d-4be5-be21-46851ac7f456.png)

- Searching for the dubbed anime:
   ![image](https://user-images.githubusercontent.com/58847957/219964348-23ca0b7c-6299-4696-b333-9b3871c3991f.png)

If you need any other info, please let me know. 

Any ideas on what could be the problem?

Thank you!

**Comment by sdaqo** [comment]
Thanks for the report! We introduced a config option some time ago where you can filter anime types (sub and dub), but forgot to document it. This option defaults to only sub, idk why. Anyway I'am gonna change this real quick.

**Comment by sdaqo** [comment]
OK this is fixed in 2.7.4, to update run the install command in the Readme.

**Comment by voidxd** [comment]
Hi. Thanks for the super quick intervention. I had a few hiccups but it works now!

I'm leaving this for posterity.

1. After updating I got this error when trying to download anime:
```
Traceback (most recent call last):
  File "/home/edxd/.local/bin/anipy-cli", line 5, in <module>
    from anipy_cli.run_anipy_cli import main
  File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/__init__.py", line 17, in <module>
    from anipy_cli.player import get_player
  File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/player/__init__.py", line 1, in <module>
    from anipy_cli.player.player import get_player, PlayerBaseType
  File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/player/player.py", line 6, in <module>
    from anipy_cli.player.players import MpvControllable, Mpv, Vlc, Syncplay
  File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/player/players/__init__.py", line 1, in <module>
    from anipy_cli.player.players.mpv_contrl import MpvControllable
  File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/player/players/mpv_contrl.py", line 1, in <module>
    import mpv
  File "/home/edxd/.local/lib/python3.10/site-packages/mpv.py", line 50, in <module>
    raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
```

And fixed it by installing:
```
apt-get install libmpv1 libavformat-dev
```

After that I noticed you changed the download argument to `D`, and it had been `d` previously.

Thank you very much for the super quick fix! It's very much appreciated!

**Comment by sdaqo** [comment]
Thanks for pointing out the libmpv thing this should actually be mandatory and only be needed when the `reuse_mpv_window` is set to true, will fix that.

**Comment by sdaqo** [comment]
> After that I noticed you changed the download argument to D, and it had been d previously.

Yeah since 2.7.0 all the modes (download, seasonal, binge etc.) have capital characters.

**Comment by Quicksilver151** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/edxd/.local/bin/anipy-cli", line 5, in <module>
>     from anipy_cli.run_anipy_cli import main
>   File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/__init__.py", line 17, in <module>
>     from anipy_cli.player import get_player
>   File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/player/__init__.py", line 1, in <module>
>     from anipy_cli.player.player import get_player, PlayerBaseType
>   File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/player/player.py", line 6, in <module>
>     from anipy_cli.player.players import MpvControllable, Mpv, Vlc, Syncplay
>   File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/player/players/__init__.py", line 1, in <module>
>     from anipy_cli.player.players.mpv_contrl import MpvControllable
>   File "/home/edxd/.local/lib/python3.10/site-packages/anipy_cli/player/players/mpv_contrl.py", line 1, in <module>
>     import mpv
>   File "/home/edxd/.local/lib/python3.10/site-packages/mpv.py", line 50, in <module>
>     raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
> OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
> ```
> 
> And fixed it by installing:
> 
> ```
> apt-get install libmpv1 libavformat-dev
> ```
> 
>     2. After that I noticed you changed the download argument to `D`, and it had been `d` previously.
> 
> 
> Thank you very much for the super quick fix! It's very much appreciated!

i also got a similar error

```
 ~/G/anipy-cli   …  ./anipy_cli.py --help                                                                                                             652ms
Traceback (most recent call last):
  File "./anipy_cli.py", line 2, in <module>
    from anipy_cli import cli
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/__init__.py", line 17, in <module>
    from anipy_cli.player import get_player
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/__init__.py", line 1, in <module>
    from anipy_cli.player.player import get_player, PlayerBaseType
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/player.py", line 6, in <module>
    from anipy_cli.player.players import Mpv, Vlc, Syncplay
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/players/__init__.py", line 1, in <module>
    from anipy_cli.player.players.mpv_contrl import MpvControllable
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/players/mpv_contrl.py", line 1, in <module>
    import mpv
  File "/home/renderinguser/.local/lib/python3.8/site-packages/mpv.py", line 11, in <module>
    backend = CDLL('libmpv.so')
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpv.so: cannot open shared object file: No such file or directory
```
and i couldnt fix it by apt installing the above mentioned stuff

**Comment by sdaqo** [comment]
@Quicksilver151 Are you running 2.7.5? I think the fix I put out for this yesterday didn't quite fix the problem, will get back if I find it. In the meantime, maybe try `libmpv-dev` idk I am not on debian , I am on arch.

**Comment by Quicksilver151** [comment]
> @Quicksilver151 Are you running 2.7.5? I think the fix I put out for this yesterday didn't quite fix the problem, will get back if I find it. In the meantime, maybe try `libmpv-dev` idk I am not on debian , I am on arch.

i always use the latest version from the repo directly

also just installed `libmpv-dev`
now im getting a new error


 `~> ./anipy_cli.py -Soq 720`
```
Traceback (most recent call last):
  File "./anipy_cli.py", line 2, in <module>
    from anipy_cli import cli
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/__init__.py", line 17, in <module>
    from anipy_cli.player import get_player
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/__init__.py", line 1, in <module>
    from anipy_cli.player.player import get_player, PlayerBaseType
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/player.py", line 6, in <module>
    from anipy_cli.player.players import Mpv, Vlc, Syncplay
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/players/__init__.py", line 1, in <module>
    from anipy_cli.player.players.mpv_contrl import MpvControllable
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/players/mpv_contrl.py", line 3, in <module>
    from anipy_cli.player.players.base import PlayerBase
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/players/base.py", line 53, in <module>
    class SubProcessPlayerBase(PlayerBase):
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/player/players/base.py", line 55, in SubProcessPlayerBase
    self, player_args_template: list[str], player_exec: str, rpc_client=None
TypeError: 'type' object is not subscriptable
```

**Comment by Quicksilver151** [comment]
oof
really sucks that my versions of python are acting weird
i have python version 3.10 installed but pip doesnt install stuff for that version
plus i cant add `#!/bin/python3.10` to files even tho there is a binary with that name
:/

**Comment by sdaqo** [comment]
I will fix it anyway but maybe you can try to use `<Your python executable> -m pip install <package>`

**Comment by Quicksilver151** [comment]
i think my very install is broken lmao
```
 !  ~/G/anipy-cli   …  python3.10 ./anipy_cli.py -Soq 720
Traceback (most recent call last):
  File "/home/renderinguser/GIT/anipy-cli/./anipy_cli.py", line 2, in <module>
    from anipy_cli import cli
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/__init__.py", line 13, in <module>
    from anipy_cli.download import download
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/download.py", line 5, in <module>
    import m3u8
ModuleNotFoundError: No module named 'm3u8'
 !  ~/G/anipy-cli   …  python3.10 -m pip install m3u8
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
 !  ~/G/anipy-cli   …  python3.10 -m pip install anything
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
```

**Comment by sdaqo** [comment]
Ok should work now. Btw you might want to look at [pyenv](https://github.com/pyenv/pyenv) if you want several python versions on your system.

**Comment by Quicksilver151** [comment]
works now
