### ISSUE TITLE
Program crashes on startup

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#120]
**Describe the bug**
program crashes at startup, regardless of what modes are selected

**To Reproduce**
run the program

**Expected behavior**
runs correctly

**Info**
error:

`~> python3 ./anipy-cli`

```Traceback (most recent call last):
  File "/home/renderinguser/CustomPath/anipy-cli", line 2, in <module>
    from anipy_cli import cli
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/__init__.py", line 13, in <module>
    from anipy_cli.download import download
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/download.py", line 16, in <module>
    from anipy_cli.misc import response_err, error, keyboard_inter
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/misc.py", line 12, in <module>
    from anipy_cli.config import Config
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/config.py", line 12, in <module>
    class Config:
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/config.py", line 162, in Config
    def _read_config():
  File "/usr/lib/python3.8/functools.py", line 526, in decorating_function
    wrapper = _lru_cache_wrapper(user_function, maxsize, typed, _CacheInfo)
TypeError: the first argument must be callable
```

**Platform**
 - OS: Linux (Kubuntu)

**Additional context**
highly suspect it to be some version incompatibility or something

**Comment by sdaqo** [comment]
yeah this is a incompatibility issue. I tried fixing it, works with python 3.9

**Comment by Quicksilver151** [comment]
works now
