### ISSUE TITLE
Error when running Anipy-cli: OSError: FFmpeg version command returned an error

### ISSUE THREAD

**Issue by haikukoten** [sdaqo/anipy-cli#121]
**Describe the bug**
Trying to download the anime using the lib

**To Reproduce**
`anipy-cli -Dq 1080`

Output
```
Downloads are stored in: /usr/local/lib/python3.10/dist-packages/anipy_cli/download
Search MyAnimeList for anime in Season? (y|n): 
>> n
Search: detective conan
Add another search: (y|n)
n

Current:  detective conan
[1] Detective Conan
[2] Detective Conan OVA
[3] Detective Conan (Dub)
[4] Detective Conan Remastered
[5] Lupin III vs. Detective Conan
[6] Meitantei Conan: Zero no Tea Time
[7] Meitantei Conan: Hannin no Hanzawa-san
[8] Detective Conan: Kid the Phantom Thief
[9] Meitantei Conan: Zero no Tea Time (Dub)
[10] Lupin III vs. Detective Conan: The Movie
[11] Detective Conan Movie 22: Zero The Enforcer
[12] Detective Conan: The Fugitive Kogorou Mouri
[13] Detective Conan Movie 12:Full Score of Fear
[14] Detective Conan Movie 13 - The Raven Chaser
[15] Meitantei Conan: Hannin no Hanzawa-san (Dub)
[16] Detective Conan Movie 24: The Scarlet Bullet
[17] Detective Conan Movie 15: Quarter of Silence
[18] Lupin III vs. Detective Conan: The Movie (Dub)
[19] Detective Conan Movie 16: The Eleventh Striker
[20] Detective Conan Movie 20: The Darkest Nightmare
[21] Detective Conan Movie 25: Halloween no Hanayome
[22] Detective Conan Movie 5 – Countdown to Heaven
[23] Detective Conan Movie 4 – Captured in Her Eyes
[24] Detective Conan Movie 22: Zero the Enforcer (Dub)
[25] Detective Conan Movie 21: The Crimson Love Letter
[26] Detective Conan Movie 19: The Hellfire Sunflowers
[27] Detective Conan Movie 2 – The Fourteenth Target
[28] Detective Conan Movie 9 - Strategy Above the Depths
[29] Detective Conan Movie 05: Countdown to Heaven (Dub)
[30] Detective Conan Movie 23: The Fist of Blue Sapphire
[31] Detective Conan Movie 14 - The Lost Ship in the Sky
[32] Detective Conan Movie 8 - Magician of the Silver Sky
[33] Detective Conan Movie 01: The Timed Skyscraper (Dub)
[34] Detective Conan Movie 04: Captured in Her Eyes (Dub)
[35] Detective Conan Movie 1 : The Time-Bombed Skyscraper
[36] Detective Conan Movie 02: The Fourteenth Target (Dub)
[37] Detective Conan Movie 10 :The Private Eyes’ Requiem
[38] Detective Conan Movie 20: The Darkest Nightmare (Dub)
[39] Detective Conan Movie 11:Jolly Roger in the Deep Azure
[40] Detective Conan Movie 19: The Hellfire Sunflowers (Dub)
[41] Detective Conan Movie 21: The Crimson Love Letter (Dub)
[42] Detective Conan: Episode One - Chiisaku Natta Meitantei
[43] Detective Conan Movie 6 – The Phantom of Baker Street
[44] Detective Conan Movie 23: The Fist of Blue Sapphire (Dub)
[45] Detective Conan Movie 7 - Crossroad in the Ancient Capital
[46] Detective Conan Movie 06: The Phantom of Baker Street (Dub)
[47] Detective Conan Movie 18: The Sniper from Another Dimension
[48] Detective Conan Movie 3 – The Last Magician of the Century
[49] Detective Conan Movie 03: The Last Wizard of the Century (Dub)
[50] Detective Conan Movie 17: Private Eye in the Distant Sea Movie
[51] Detective Conan: Episode One - The Great Detective Turned Small
[52] Detective Conan: Love Story at Police Headquarters - Wedding Eve
[53] Detective Conan: Episode One - The Great Detective Turned Small (Dub)
Enter Number: 1
Episode (Range with '-') [1-1079] Special Eps: 124.125, 203.204, 212.213, 274.275, 297.298, 301.302, 305.306, 316.317, 348.349, 1077.5
>> 13
--------------------
Downloading: Detective Conan EP: 13 - auto
Type: m3u8
Downloader:internal
Playlist Index: 0
Resolution at this index: (640, 480)


Playlist Index: 1
Resolution at this index: (480, 360)


Quality for Download:(640, 480)


Downloading  Part: 345/345
Parts Downloaded
Merging Parts using Movie.py...
Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command returned an error
Traceback (most recent call last):
  File "/usr/local/bin/anipy-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/anipy_cli/run_anipy_cli.py", line 8, in main
    cli.run_cli()
  File "/usr/local/lib/python3.10/dist-packages/anipy_cli/cli/cli.py", line 37, in run_cli
    cli_class(options=args, rpc_client=rpc_client).run()
  File "/usr/local/lib/python3.10/dist-packages/anipy_cli/cli/clis/base_cli.py", line 36, in run
    self.process()
  File "/usr/local/lib/python3.10/dist-packages/anipy_cli/cli/clis/download_cli.py", line 86, in process
    download(entry, self.options.quality, self.options.ffmpeg).download()
  File "/usr/local/lib/python3.10/dist-packages/anipy_cli/download.py", line 94, in download
    self.multithread_m3u8_dl()
  File "/usr/local/lib/python3.10/dist-packages/anipy_cli/download.py", line 309, in multithread_m3u8_dl
    self.ffmpeg_merge(input_file, audio_input_file)
  File "/usr/local/lib/python3.10/dist-packages/anipy_cli/download.py", line 163, in ffmpeg_merge
    ffmpeg_tools.ffmpeg_merge_video_audio(
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/ffmpeg_tools.py", line 52, in ffmpeg_merge_video_audio
    subprocess_call(cmd, logger = logger)
  File "/usr/local/lib/python3.10/dist-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
```

**Expected behavior**
Files to be downloaded

**Info**
Name: anipy-cli
```
Version: 2.7.14
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: beautifulsoup4, better-ffmpeg-progress, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, python-mpv, pyyaml, requests, setuptools, tqdm
Required-by:
 ```

**Platform**
 - OS: Linux
 - Maybe something else that is specific to your platform and may have impact on the bug

**Additional context**

**Comment by sdaqo** [comment]
Maybe you have a faulty ffmpeg install? It's really hard to say given there is no real error here and I mayself don't face this error. Maybe try ffmpeg on its own and look how it goes. Another thing that could be that moviepy is broken for you (try updating with `pip install moviepy --upgrade`). Other then that its hard to say.

**Comment by sdaqo** [comment]
Stale issue, closing.
