### ISSUE TITLE
JSON decode error while syncing from MAL

### ISSUE THREAD

**Issue by Prashanthvsdvn** [sdaqo/anipy-cli#122]
**Describe the bug**
The script breaks when I am trying to sync MAL list to seasonal. It happens when processing Fate/Zero I guess. Attaching the log in the bottom

**To Reproduce**
1. Have Fate/Zero in MAL list
2. Open script in MAL mode
3. Try to sync MAL list to seasonal
4. JSON decode error

**Expected behavior**
Script should not error out here

**Info**
```
Name: anipy-cli
Version: 2.7.10
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: C:\Python311\Lib\site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, python-mpv, pyyaml, requests, setuptools, tqdm
Required-by:
```

**Platform**
 - OS: Windows 10

**Additional context**
Attaching Trace-back here
```
Auto mapping: Fate/stay night Movie: Heaven's Feel - I. Presage Flower
Auto mapping: Fate/stay night Movie: Heaven's Feel - II. Lost Butterfly
Auto mapping: Fate/stay night: Unlimited Blade Works
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python311\Lib\multiprocessing\pool.py", line 579, in _handle_results
    task = get()
Auto mapping: Fate/Zero
           ^^^^^
  File "C:\Python311\Lib\multiprocessing\connection.py", line 250, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\exceptions.py", line 41, in __init__
Auto mapping: Fate/Zero 2nd Season
    CompatJSONDecodeError.__init__(self, *args)
TypeError: JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'
```

**Comment by sdaqo** [comment]
I actually don't really know whats going on here. The traceback does not provide any proper info as to where the error happned, probably because it's running in another thread. I guess you could just try manually mapping some of the shows that throw errors, other then that maybe delete your mal_list.json and try again

**Comment by Prashanthvsdvn** [comment]
Is it possible to alter to soft fail and return list of failed mappings instead of hard fail?

**Comment by sdaqo** [comment]
Will close it for now
