### ISSUE TITLE
downloading anime now causes issues

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#14]
i ran main.py with download flag
```
./main.py -dq 480                         
```

when i searched for anime, it crashed
```
***Download Mode***
Downloads are stored in: /home/renderinguser/GIT/anipy-cli/download
Search for Anime: saenai
Traceback (most recent call last):                                     
  File "./main.py", line 4, in <module>                                
    from src import query, play, history, menu, download, url          
  File "/home/renderinguser/GIT/anipy-cli/src/query.py", line 3, in <module>
    from main import config
  File "/home/renderinguser/GIT/anipy-cli/main.py", line 53, in <module>
    download.main_activity()
  File "/home/renderinguser/GIT/anipy-cli/src/download.py", line 95, in main_activity
    link = query.query(search)
AttributeError: partially initialized module 'src.query' has no attribute 'query' (most likely due to a circular import)
```

**Comment by Dabbing-Guy** [comment]
I just created a pull request that fixes the issue you are having. If you want the patch code right now, you can get it from [my fork](https://github.com/Dabbing-Guy/anipy-cli).
