### ISSUE TITLE
Just clean installed and get the following error

### ISSUE THREAD

**Issue by Danneke12** [sdaqo/anipy-cli#142]
Hi, i just installed it on a clean Debian 11 VPS
And i'm getting the following error, i'm also including my steps:
Python3 version : Python 3.11.5

```
root@MainServer:~/.config/anipy-cli# anipy-cli -D
***Download Mode***
Downloads are stored in: /home/anime/{show_name}
Search MyAnimeList for anime in Season? (y|n):
n
Search: the greatest demon lord
Add another search: (y|n)
n

Current:  the greatest demon lord
[1] Shijou Saikyou no Daimaou, Murabito A ni Tensei suru
[2] Shijou Saikyou no Daimaou, Murabito A ni Tensei suru (Dub)
Enter Number: 1
Episode (Range with '-') [1-12]
2
--------------------
Downloading: Shijou Saikyou no Daimaou, Murabito A ni Tensei suru EP: 2 - hls
Type: m3u8
Downloader:internal
Playlist Index: 0
Resolution at this index: (1920, 1080)


Playlist Index: 1
Resolution at this index: (1280, 720)


Playlist Index: 2
Resolution at this index: (854, 480)


Playlist Index: 3
Resolution at this index: (640, 360)


Quality for Download:(1920, 1080)


Downloading  Part: 349/349
Parts Downloaded
Merging Parts using Movie.py...
Moviepy - Running:
"+ " ".join(cmd)
Moviepy - Command returned an error
Traceback (most recent call last):
  File "/usr/local/bin/anipy-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/anipy_cli/run_anipy_cli.py", line 8, in main
    cli.run_cli()
  File "/usr/local/lib/python3.11/dist-packages/anipy_cli/cli/cli.py", line 37, in run_cli
    cli_class(options=args, rpc_client=rpc_client).run()
  File "/usr/local/lib/python3.11/dist-packages/anipy_cli/cli/clis/base_cli.py", line 36, in run
    self.process()
  File "/usr/local/lib/python3.11/dist-packages/anipy_cli/cli/clis/download_cli.py", line 86, in process
    download(entry, self.options.quality, self.options.ffmpeg).download()
  File "/usr/local/lib/python3.11/dist-packages/anipy_cli/download.py", line 93, in download
    self.multithread_m3u8_dl()
  File "/usr/local/lib/python3.11/dist-packages/anipy_cli/download.py", line 308, in multithread_m3u8_dl
    self.ffmpeg_merge(input_file, audio_input_file)
  File "/usr/local/lib/python3.11/dist-packages/anipy_cli/download.py", line 162, in ffmpeg_merge
    ffmpeg_tools.ffmpeg_merge_video_audio(
  File "/usr/local/lib/python3.11/dist-packages/moviepy/video/io/ffmpeg_tools.py", line 52, in ffmpeg_merge_video_audio
    subprocess_call(cmd, logger = logger)
  File "/usr/local/lib/python3.11/dist-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
```

**Comment by DragonOfShuu** [comment]
What is the output of this command?
```
pip show anipy-cli
```

**Comment by stanpai78** [comment]
Found a workaround for this BUT you have to use the seasonals feature for this:
use the the `-S` argument (`anipy-cli -S`)
add the anime to the list
find the seasonals file
default on windows is:
`%localappdata%\Programs\Python\Python311\Lib\site-packages\anipy_cli\user_files\seasonals.json`
remove the , from the name
then watch/download from seasonal mode

**Comment by sdaqo** [comment]
`Downloads are stored in: /home/anime/{show_name}`
Your path to the downloads may not have {show_name} in the name as a format field. A drectory will be created for each series anyway under the downloads_path.
