### ISSUE TITLE
Episodes not Listing Properly

### ISSUE THREAD

**Issue by Prashanthvsdvn** [sdaqo/anipy-cli#150]
**Describe the bug**
When trying to view the episodes from a series, the episodes listings are not available and the options only exists as [0-0]. I'm not sure if something is broken in the backend of gogo.

**To Reproduce**
1. Open `anipy-cli`
2. Search for any series. (Search Results of Series is returned properly)
3. Only episode index is 0-0
4. Any other episode index no. is returned by a `Number is outside of index range` for a split second

**Expected behavior**
Correct Episode No. should be displayed.

**Info**
```
Version: 2.7.30
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: C:\Python312\Lib\site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, python-mpv, pyyaml, requests, setuptools, tqdm, yaspin
Required-by:
```

**Platform**
 - OS: Windows 11

**Additional context**
Add any other context about the problem here, e.g. your config if related.

**Comment by S0litaire** [comment]
Same here! 
Any search using "anipy-cli -D" comes back 0 episodes, no matter the title searched.

looks like it's an issue at "gogoanime" end since "ajax.gogo-load.com" was down over the weekend and is having ssl cert issues.

You might just have to wait it out for a few days for things to sort themselves out.


This is the error I'm getting when running :
`anipy-cli -M`
selecting option:
 ` [x] Download all episodes`
I get the following error :
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 405, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'ajax.gogo-load.com' doesn't match either of '*.apnigiftshop.com', 'apnigiftshop.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 800, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ajax.gogo-load.com', port=443): Max retries exceeded with url: /ajax/load-list-episode?ep_start=0&ep_end=9999&id=14111 (Caused by SSLError(CertificateError("hostname 'ajax.gogo-load.com' doesn't match either of '*.apnigiftshop.com', 'apnigiftshop.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bill/.local/bin/anipy-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/run_anipy_cli.py", line 8, in main
    cli.run_cli()
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/cli/cli.py", line 37, in run_cli
    cli_class(options=args, rpc_client=rpc_client).run()
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/cli/clis/base_cli.py", line 38, in run
    self.post()
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/cli/clis/mal_cli.py", line 27, in post
    menu.run()
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/cli/menus/base_menu.py", line 32, in run
    self.take_input()
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/cli/menus/base_menu.py", line 43, in take_input
    op.callback()
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/cli/menus/mal_menu.py", line 98, in <lambda>
    MenuOption("Download all episodes", lambda: self.download(mode="all"), "x"),
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/cli/menus/mal_menu.py", line 206, in download
    urls = self.m_class.latest_eps(all_eps=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/mal.py", line 483, in latest_eps
    latest = ep_class.get_latest()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/url_handler.py", line 107, in get_latest
    ep_list = self._load_eps_list()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bill/.local/lib/python3.11/site-packages/anipy_cli/url_handler.py", line 50, in _load_eps_list
    res = requests.get(
          ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ajax.gogo-load.com', port=443): Max retries exceeded with url: /ajax/load-list-episode?ep_start=0&ep_end=9999&id=14111 (Caused by SSLError(CertificateError("hostname 'ajax.gogo-load.com' doesn't match either of '*.apnigiftshop.com', 'apnigiftshop.com'")))

```

**Comment by Prashanthvsdvn** [comment]
Yup. I was getting SSL errors intermittently when trying to access the episodes. But I think the website was functioning normally (or at-least for me). 

Do you guys think there might a change in the way backend is accessed that we might need to replicate here?

**Comment by sdaqo** [comment]
Will look into it later today! Thanks for the report.

**Comment by sdaqo** [comment]
works again
