### ISSUE TITLE
[Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ZanDev32** [sdaqo/anipy-cli#153]
**Describe the bug**
i just clean install this tool and i got an error message 

**To Reproduce**
1. `ani-cli 'any random anime'`
2. the error show up

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7429d87a6680>: Failed to resolve 'gogoanime.vet' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gogoanime.vet', port=443): Max retries exceeded with url: ///search.html?keyword=tate%20no%20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7429d87a6680>: Failed to resolve 'gogoanime.vet' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/{user}/.local/bin/anipy-cli", line 8, in <module>
    sys.exit(main())
  File "/home/{user}/.local/lib/python3.10/site-packages/anipy_cli/run_anipy_cli.py", line 8, in main
    cli.run_cli()
  File "/home/{user}/.local/lib/python3.10/site-packages/anipy_cli/cli/cli.py", line 37, in run_cli
    cli_class(options=args, rpc_client=rpc_client).run()
  File "/home/{user}/.local/lib/python3.10/site-packages/anipy_cli/cli/clis/base_cli.py", line 35, in run
    self.take_input()
  File "/home/{user}/.local/lib/python3.10/site-packages/anipy_cli/cli/clis/default_cli.py", line 24, in take_input
    user_query = query(inp, self.entry)
  File "/home/{user}/.local/lib/python3.10/site-packages/anipy_cli/query.py", line 30, in __init__
    r = requests.get(self.search_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gogoanime.vet', port=443): Max retries exceeded with url: ///search.html?keyword=tate%20no%20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7429d87a6680>: Failed to resolve 'gogoanime.vet' ([Errno -2] Name or service not known)"))
```

**Expected behavior**
start playing the anime

**Info**
Name: anipy_cli
Version: 2.7.31
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /home/asus/.local/lib/python3.10/site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, python-mpv, pyyaml, requests, setuptools, tqdm, yaspin
Required-by:

**Platform**
 - OS: GNU/POP OS 22.04

**Additional context**
just reply if you need more information

**Comment by sdaqo** [comment]
can you edit your config and set `gogoanime_url: https://gogoanime3.co/` and try again?

**Comment by sdaqo** [comment]
Can not really tell you how to fix that as I do not really now whats going on on your side, but you if you wait for v3 release your problem might be fixed...

**Comment by sdaqo** [comment]
Alright, thanks for investing!

**Comment by sdaqo** [comment]
This may be some kind of network configuration error can you send me your ouput of these commands (I posted my output for comparison): 
```
$ nslookup gogoanime3.co
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	gogoanime3.co
Address: 172.67.69.148
Name:	gogoanime3.co
Address: 104.26.14.170
Name:	gogoanime3.co
Address: 104.26.15.170
Name:	gogoanime3.co
Address: 2606:4700:20::681a:eaa
Name:	gogoanime3.co
Address: 2606:4700:20::ac43:4594
Name:	gogoanime3.co
Address: 2606:4700:20::681a:faa
```

```
$ nslookup gogoanime.vet
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find gogoanime.vet: NXDOMAIN

```
```
$ curl -I https://gogoanime3.co/
HTTP/2 200 
date: Wed, 24 Apr 2024 14:30:36 GMT
content-type: text/html; charset=utf-8
vary: Accept-Encoding
x-powered-by: PHP/5.6.13
set-cookie: gogoanime=kv9rh0scquf8t04pdq47ca59v6; path=/
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
pragma: no-cache
cf-cache-status: DYNAMIC
```
For this one please cut out your mal login data and other personal stuff:
```
$ cat $(anipy-cli --config)
anime_types:
- sub
- dub
auto_map_mal_to_gogo: false
auto_open_dl_defaultcli: false
auto_sync_mal_to_seasonals: false
dc_presence: false
download_folder_path: ~/anime
download_name_format: '{show_name}_{episode_number}.mp4'
download_remove_dub_from_folder_name: false
ffmpeg_hls: false
ffmpeg_log_path: ~/.local/share/anipy-cli/ffmpeg_log
gogoanime_url: https://gogoanime3.co/
history_file_path: ~/.local/share/anipy-cli/history.json
mal_local_user_list_path: ~/.local/share/anipy-cli/mal_list.json
mal_password: ''
mal_status_categories:
- watching
mal_user: ''
mpv_commandline_options:
- --keep-open=no
player_path: mpv
reuse_mpv_window: false
seasonal_file_path:  ~/.local/share/anipy-cli/seasonals.json
seasonals_dl_path:  ~/.local/share/anipy-cli/seasonals
user_files_path: ~/.local/share/anipy-cli/user_files
vlc_commandline_options: []
```

**Comment by sdaqo** [comment]
maybe remove the second slash in the gogoanime url at the end? Other then that everything looks fine? I honestly do not know why you get a result for gogoanime.vat, but oh well...

**Comment by sdaqo** [comment]
please check with the new version: https://sdaqo.dev/anipy-cli/getting-started-cli/

**Comment by sdaqo** [comment]
Stale, closing
