### ISSUE TITLE
anime with unknown charachters crashes the program

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#16]
its the same issue i faced with the shell script ani-cli

when an anime title has an uncommon symbol like in `Saenai Heroine no Sodatekata ♭`, it fails to download
that is the name of the second season of saenai heroine
selecting an episode from that results in the error message:
```
Getting emebed-urls                                                    
Traceback (most recent call last):                                     
  File "/home/renderinguser/GIT/anipy-cli/main.py", line 11, in <module>                                                                      
    from src import query, play, history, menu, download, url          
  File "/home/renderinguser/GIT/anipy-cli/src/menu.py", line 3, in <module>                                                                   
    import main
  File "/home/renderinguser/GIT/anipy-cli/main.py", line 60, in <module>
    download.main_activity()
  File "/home/renderinguser/GIT/anipy-cli/src/download.py", line 104, in main_activity
    embeded_urls.append(url.get_embed_url(j))
  File "/home/renderinguser/GIT/anipy-cli/src/url.py", line 63, in get_embed_url
    return f'https:{link["data-video"]}'
TypeError: 'NoneType' object is not subscriptable
```

heres the link to the issue in ani-cli
i believe the issue discusses the solution so i hope it helps
https://github.com/pystardust/ani-cli/issues/240#issuecomment-1003370426

**Comment by sdaqo** [comment]
Should work now.  I would appreciate if you could try it!

**Comment by sdaqo** [comment]
Oh wait I just found something myself.

**Comment by Quicksilver151** [comment]
didnt work
got this abnormally large error
```
Getting emebed-urls                                                    
Traceback (most recent call last):                                     
  File "/home/renderinguser/GIT/anipy-cli/src/url.py", line 61, in get_embed_url                                                              
    r = requests.get(url[0])                                           
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get                                              
    return request('get', url, params=params, **kwargs)                
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request                                          
    return session.request(method=method, url=url, **kwargs)           
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request                                    
    prep = self.prepare_request(req)                                   
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request                            
    p.prepare(                                                         
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare                                      
    self.prepare_url(url, params)                                      
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url                                  
    raise MissingSchema(error)                                         
requests.exceptions.MissingSchema: Invalid URL 'h': No schema supplied. Perhaps you meant http://h?                                           

During handling of the above exception, another exception occurred:    

Traceback (most recent call last):                                     
  File "/home/renderinguser/GIT/anipy-cli/main.py", line 11, in <module>                                                                      
    from src import query, play, history, menu, download, url          
  File "/home/renderinguser/GIT/anipy-cli/src/menu.py", line 3, in <module>                                                                   
    import main                                                        
  File "/home/renderinguser/GIT/anipy-cli/main.py", line 60, in <module>                                                                      
    download.main_activity()                                           
  File "/home/renderinguser/GIT/anipy-cli/src/download.py", line 104, in main_activity                                                        
    embeded_urls.append(url.get_embed_url(j))                          
  File "/home/renderinguser/GIT/anipy-cli/src/url.py", line 67, in get_embed_url                                                              
    r = requests.get(url[1])                                           
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get                                              
    return request('get', url, params=params, **kwargs)                
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request                                          
    return session.request(method=method, url=url, **kwargs)           
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request                                    
    prep = self.prepare_request(req)                                   
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 't': No schema supplied. Perhaps you meant http://t?
```

**Comment by sdaqo** [comment]
could you try again?

**Comment by Quicksilver151** [comment]
it worked
