### ISSUE TITLE
Episode 0 throws error

### ISSUE THREAD

**Issue by GreatTeacherOni** [sdaqo/anipy-cli#182]
**Describe the bug**
Some anime shows have an episode 0, e.g. Sengoku Youko: Senma Konton-hen.

CLI output shows following output with error:
```
? Do you want to search in season? No
Hint: you can set `skip_season_search` to `true` in the config to skip this prompt!
? Search Anime: Sengoku Youko: Senma Konton-hen
? Select Show: 1. GO: Sengoku Youko: Senma Konton-hen (S)
? Select Episode: 0
Traceback (most recent call last):
  File "/nix/store/3sa2xhvvypnv8mc4vskhlhvcpwhs31bx-python3.11-anipy-cli-3.1.7/bin/.anipy-cli-wrapped", line 9, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/nix/store/3sa2xhvvypnv8mc4vskhlhvcpwhs31bx-python3.11-anipy-cli-3.1.7/lib/python3.11/site-packages/anipy_cli/cli.py", line 60, in run_cli
    cli_class(options=args).run()
  File "/nix/store/3sa2xhvvypnv8mc4vskhlhvcpwhs31bx-python3.11-anipy-cli-3.1.7/lib/python3.11/site-packages/anipy_cli/clis/base_cli.py", line 31, in run
    ret = func()
          ^^^^^^
  File "/nix/store/3sa2xhvvypnv8mc4vskhlhvcpwhs31bx-python3.11-anipy-cli-3.1.7/lib/python3.11/site-packages/anipy_cli/clis/default_cli.py", line 81, in process
    self.stream = self.anime.get_video(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nwcnmqfybg0ci7mywz3kxjrfvgp9w2ng-python3.11-anipy-api-3.1.7/lib/python3.11/site-packages/anipy_api/anime.py", line 116, in get_video
    streams = self.provider.get_video(self.identifier, episode, lang)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/nwcnmqfybg0ci7mywz3kxjrfvgp9w2ng-python3.11-anipy-api-3.1.7/lib/python3.11/site-packages/anipy_api/provider/providers/gogo_provider.py", line 278, in get_video
    raise LangTypeNotAvailableError(identifier, self.NAME, lang)
anipy_api.error.LangTypeNotAvailableError: Sub is not available for identifier `sengoku-youko-senma-konton-hen` on provider `gogoanime`
```

**To Reproduce**
Search for any anime that has an episode 0

**Expected behavior**
Episode 0 starts in configured player

**Info**
Post your output of `pip show anipy-cli`
I ran anipy-cli from cloned gitrepo (flake.nix / shell.nix) so no pip output available
anipy-cli version: 3.1.7

**Platform**
 - OS: 24.11pre

**Comment by sdaqo** [comment]
uhm btw, this episode "0" is just gogoanime being funny and putting a episode 0 even if the anime has no episode out yet...
