### ISSUE TITLE
Nix profile installed version of anipy failed to run

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#194]
**Describe the bug**
i installed anipy-cli with nix profile
install succeeded
but running anipy-cli crashes the program

**To Reproduce**
```
$ nix --version
nix (Nix) 2.20.1

$ nix --extra-experimental-features flakes --extra-experimental-features nix-command profile install github:sdaqo/anipy-cli
[0.3/0.0 MiB DL] downloading 'https://github.com/sdaqo/anipy-cli/archive/e9a4b2716f0b9d2a6c22b505db96b32warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled

$ anipy-cli
Traceback (most recent call last):
  File "/home/renderinguser/.local/bin/anipy-cli", line 11, in <module>
    load_entry_point('anipy-cli==2.7.12', 'console_scripts', 'anipy-cli')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/anipy_cli-2.7.12-py3.8.egg/anipy_cli/__init__.py", line 13, in <module>
    from anipy_cli.download import download
  File "/usr/local/lib/python3.8/dist-packages/anipy_cli-2.7.12-py3.8.egg/anipy_cli/download.py", line 16, in <module>
    from anipy_cli.misc import response_err, error, keyboard_inter
  File "/usr/local/lib/python3.8/dist-packages/anipy_cli-2.7.12-py3.8.egg/anipy_cli/misc.py", line 12, in <module>
    from anipy_cli.config import Config
  File "/usr/local/lib/python3.8/dist-packages/anipy_cli-2.7.12-py3.8.egg/anipy_cli/config.py", line 12, in <module>
    class Config:
  File "/usr/local/lib/python3.8/dist-packages/anipy_cli-2.7.12-py3.8.egg/anipy_cli/config.py", line 162, in Config
    def _read_config():
  File "/usr/lib/python3.8/functools.py", line 526, in decorating_function
    wrapper = _lru_cache_wrapper(user_function, maxsize, typed, _CacheInfo)
TypeError: the first argument must be callable
```

**Expected behavior**
anipy-cli to run without crashing

**Info**
Post your output of `pip show anipy-cli`
irrelevant i guess

**Platform**
 - OS: Kubuntu 20.04

**Comment by Quicksilver151** [comment]
nvm im an idiot
```
$ which anipy-cli
╭───┬───────────┬──────────────────────────────────────────┬──────────╮
│ # │  command  │                   path                   │   type   │
├───┼───────────┼──────────────────────────────────────────┼──────────┤
│ 0 │ anipy-cli │ /home/renderinguser/.local/bin/anipy-cli │ external │
╰───┴───────────┴──────────────────────────────────────────┴──────────╯
```

```
$ ~/.nix-profile/bin/anipy-cli
``` 
^ that works
