### ISSUE TITLE
API yugenanime might be down forever

### ISSUE THREAD

**Issue by someonecantcode** [sdaqo/anipy-cli#212]
**Describe the bug**
When searching for anime, errors arise in http request.

**To Reproduce**
1. run anipy-ci
2. search for any anime
3. See error
```
←[K←[?25hTraceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Scripts\anipy-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\anipy_cli\cli.py", line 60, in run_cli
    cli_class(options=args).run()
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\anipy_cli\clis\base_cli.py", line 31, in run
    ret = func()
          ^^^^^^
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\anipy_cli\clis\download_cli.py", line 55, in take_input
    anime = self._get_anime_from_user()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\anipy_cli\clis\download_cli.py", line 46, in _get_anime_from_user
    return search_show_prompt("download")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\anipy_cli\prompts.py", line 53, in search_show_prompt
    for x in provider.get_search(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\anipy_api\provider\providers\yugen_provider.py", line 94, in get_search
    res = self._request_page(req).json()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\anipy_api\provider\base.py", line 156, in _request_page
    return request_page(self.session, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\anipy_api\provider\utils.py", line 26, in request_page
    res.raise_for_status()
  File "C:\Users\LabTea\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 522 Server Error:  for url: https://yugenanime.tv/api/discover/?q=jjk&page=1
```

**Expected behavior**
Should be able to request data

**Info**
Yugenanime currently is down and might be closing down soon.

**Platform**
 - OS: Windows 10
 - Python: Python 3.11.4
 - Pip: pip 24.3.1

**Comment by sdaqo** [comment]
Yeah the solution has already been discussed in #210, I will remove the provider after adding a new one

**Comment by kulindu-boop** [comment]
I also have the same issue, and I downloaded the 3.2.4 version

**Comment by sdaqo** [comment]
removed and replaced with another provider int 3.3.0
