### ISSUE TITLE
Can we use VLC to watch anime in anipy-cli

### ISSUE THREAD

**Issue by kulindu-boop** [sdaqo/anipy-cli#220]
hi, this isn't a request, more of a question, but is it possible to use VLC to watch anime while using anipy-cli?

**Comment by sdaqo** [comment]
yeah, you can either specify it in you config or pass `-p vlc` as an argument.

**Comment by kulindu-boop** [comment]
how do u specify it in the config

**Comment by kulindu-boop** [comment]
how to specify vlc in config

**Comment by sdaqo** [comment]
which platform are you on? If vlc is included in PATH (i.e. you can type 'vlc' in your terminal and it opens) then you should be able to just put 'vlc' in the player path: `player_path: vlc`

**Comment by sdaqo** [comment]
also which error?

**Comment by kulindu-boop** [comment]
> also, which error?

Traceback (most recent call last):
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_api\player\base.py", line 169, in _open_sproc
    sub_proc = sp.Popen(player_command)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL Latitude 7390\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\DELL Latitude 7390\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\DELL Latitude 7390\Desktop\projects\.venv\Scripts\anipy-cli.exe\__main__.py", line 7, in <module>
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_cli\cli.py", line 60, in run_cli
    cli_class(options=args).run()
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_cli\clis\base_cli.py", line 31, in run
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_cli\cli.py", line 60, in run_cli
    cli_class(options=args).run()
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_cli\clis\base_cli.py", line 31, in run
    ret = func()
    ret = func()
          ^^^^^^
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_cli\clis\default_cli.py", line 102, in show
    self.player.play_title(self.anime, self.stream)
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_api\player\base.py", line 147, in play_title
    self._sub_proc = self._open_sproc(player_cmd)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_api\player\base.py", line 175, in _open_sproc
    raise PlayerError(f"Executable {player_command[0]} was not found")
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_cli\clis\default_cli.py", line 102, in show
    self.player.play_title(self.anime, self.stream)
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_api\player\base.py", line 147, in play_title
    self._sub_proc = self._open_sproc(player_cmd)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_api\player\base.py", line 175, in _open_sproc
    raise PlayerError(f"Executable {player_command[0]} was not found")
    self._sub_proc = self._open_sproc(player_cmd)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_api\player\base.py", line 175, in _open_sproc
    raise PlayerError(f"Executable {player_command[0]} was not found")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_api\player\base.py", line 175, in _open_sproc
    raise PlayerError(f"Executable {player_command[0]} was not found")
  File "c:\Users\DELL Latitude 7390\Desktop\projects\.venv\Lib\site-packages\anipy_api\player\base.py", line 175, in _open_sproc
    raise PlayerError(f"Executable {player_command[0]} was not found")
    raise PlayerError(f"Executable {player_command[0]} was not found")
anipy_api.error.PlayerError: Executable vlc was not found
PS C:\Users\DELL Latitude 7390\Desktop\projects>

**Comment by kulindu-boop** [comment]
> which platform are you on? If vlc is included in PATH (i.e. if you can type 'vlc' in your terminal and it opens) then you should be able to just put 'vlc' in the player path: `player_path: vlc`

I use python in VScode

**Comment by sdaqo** [comment]
https://www.vlchelp.com/add-vlc-command-prompt-windows/ then try again, or just put the full path to the VLC exe in the config

**Comment by kulindu-boop** [comment]
ok now it works, thank you for ur help, i really appreciate it.
