### ISSUE TITLE
program no longer works for me

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#27]
heres a copy of the contents on the terminal

```
anipy-cli -dq 480                                                                                                                                                        6s
***Download Mode***
Downloads are stored in: /media/renderinguser/PC Disk EXT/anipy-cli/download
Search for Anime: sono bisque
[1] sono-bisque-doll-wa-koi-wo-suru
[2] sono-bisque-doll-wa-koi-wo-suru-dub
Enter Number: 1
Episode [1-7]: 1                                                                                                                                                                    
Getting embed url for sono-bisque-doll-wa-koi-wo-suru-episode-1
Getting video url for sono-bisque-doll-wa-koi-wo-suru-episode-1
Something went wrong with the quality selection. Loading default quality.
Traceback (most recent call last):
  File "/media/renderinguser/PC Disk EXT/anipy-cli/main.py", line 116, in <module>
    download.main_activity()
  File "/media/renderinguser/PC Disk EXT/anipy-cli/src/download.py", line 103, in main_activity
    get_links(episode_urls, config.download_folder_path)    
  File "/media/renderinguser/PC Disk EXT/anipy-cli/src/download.py", line 127, in get_links
    download(video_url, embed_url[0], p, folder_path)
  File "/media/renderinguser/PC Disk EXT/anipy-cli/src/download.py", line 13, in download
    resp = requests.get(video_url, headers={'referer': embed_url}, stream=True)
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/renderinguser/.local/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```
every time it now seems that anime quality selection always fails
and then it proceeds to fail downloading all together

ok seems like watch mode fails as well

it seems that the program is unable to fetch the link

**Comment by sdaqo** [comment]
Hi, thanks for reporting. Gogoanime changed their methodes again, well this time they just changed it back to what it was before so I can reuse some code.  It will be faster now since no webdriver is required anymore. I will patch it, it will take some time though, maybe 1 or 2 days (dont quote me on that).

**Comment by sdaqo** [comment]
Look at #28
