### ISSUE TITLE
Program breaks when trying to stream

### ISSUE THREAD

**Issue by Prashanthvsdvn** [sdaqo/anipy-cli#42]
**Describe the bug**
Selecting a bug breaks the program with an Unicode Decode error. I get error logs like these.
```
Traceback (most recent call last):
File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Python310\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\Python310\Scripts\anipy-cli.exe\__main__.py", line 7, in <module>
File "C:\Python310\lib\site-packages\anipy_cli\run_anipy_cli.py", line 7, in main
cli.main()
File "C:\Python310\lib\site-packages\anipy_cli\cli.py", line 494, in main
default_cli(args.quality)
File "C:\Python310\lib\site-packages\anipy_cli\cli.py", line 41, in default_cli
url_class.stream_url()
File "C:\Python310\lib\site-packages\anipy_cli\url_handler.py", line 230, in stream_url
id = id[: id.index(b"&")].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte 
```

**To Reproduce**
1. Try to stream any anime episode

**Expected behavior**
Mpv should launch and stream the episode

**Info**
```
WARNING: Ignoring invalid distribution -nipy-cli (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
Name: anipy-cli
Version: 2.2.6
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: c:\python310\lib\site-packages
Requires: bs4, pycryptodomex, requests, tqdm
Required-by:
```

**Platform**
 - OS: Windows

**Additional context**
I suspect gogo is changing something again with the website. The folks at ani-cli also mentioned their script is breaking due to gogo constantly changing something from their end. Not sure if its the same root cause here.

**Comment by sdaqo** [comment]
Pushed a fix download version `2.2.8`
