### ISSUE TITLE
Error with playing episodes 

### ISSUE THREAD

**Issue by Dabbing-Guy** [sdaqo/anipy-cli#43]
**Describe the bug**

An error is raised when the program tries to play an episode.

**To Reproduce**

Here is the full interaction that I had to get this error. This was achieved with a fresh install of anipy-cli. I even `rm -rf`ed my site-packages/anipy_cli after uninstalling.

```
❯ anipy-cli
Search: sword art online
[1] Sword Art Online
[2] Sword Art Online II
[3] Sword Art Online (Dub)
[4] Sword Art Online Specials
[5] Sword Art Online II (Dub)
[6] Sword Art Online: Alicization
[7] Sword Art Online: Extra Edition
[8] Sword Art Online II Episode 14.5
[9] Sword Art Online: Alicization (Dub)
[10] Sword Art Online Movie: Ordinal Scale
[11] Sword Art Online: Extra Edition (Dub)
[12] Sword Art Online II: Sword Art Offline II
[13] Sword Art Online Movie: Ordinal Scale (Dub)
[14] Sword Art Online Alternative: Gun Gale Online
[15] Sword Art Online: Alicization - War of Underworld
[16] Sword Art Online: Sword Art Offline - Extra Edition
[17] Sword Art Online Alternative - Gun Gale Online (Dub)
[18] Sword Art Online: Alicization - War of Underworld (Dub)
[19] Sword Art Online: Alicization - War of Underworld 2nd Season
[20] Sword Art Online: Progressive Movie - Hoshi Naki Yoru no Aria
[21] Sword Art Online: Alicization - War of Underworld 2nd Season (Dub)
Enter Number: 3
Episode [1-25]: 1
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/anipy-cli", line 12, in <module>
    main()
  File "/usr/local/bin/anipy-cli", line 7, in main
    cli.main()
  File "/home/michael/.local/lib/python3.10/site-packages/anipy_cli/cli.py", line 506, in main
    default_cli(args.quality)
  File "/home/michael/.local/lib/python3.10/site-packages/anipy_cli/cli.py", line 41, in default_cli
    url_class.stream_url()
  File "/home/michael/.local/lib/python3.10/site-packages/anipy_cli/url_handler.py", line 244, in stream_url
    self.aes_decrypt(r.json().get("data")).strip(
  File "/home/michael/.local/lib/python3.10/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and ep.status != 5 order by type_id asc, status DESC' at line 3<br>: 0
```

**Expected behavior**
The episode gets played.

**Info**
```
Name: anipy-cli
Version: 2.2.8
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /home/michael/.local/lib/python3.10/site-packages
Requires: bs4, pycryptodomex, requests, tqdm
Required-by:
```
Also note that anipy-cli was installed from PyPI, not github

**Platform**
 - OS: Artix Linux. Running python 3.10.4. Running requests version 2.27.1

**Comment by sdaqo** [comment]
hi, thanks for reporting updated everything, also the pip version, could you let me know if it works?

**Comment by Dabbing-Guy** [comment]
It is working now. Thanks for your help!
