### ISSUE TITLE
Downloads not starting due to bad path name

### ISSUE THREAD

**Issue by Prashanthvsdvn** [sdaqo/anipy-cli#76]
**Describe the bug**
When trying to download episodes, the downloader produces incorrect path name and it is unable to create a directory with the same name, thereby crashing the script.

**To Reproduce**
1. Open `anipy-cli -d`
2. Say no to search via Kitsu
3. Search for series and episode
4. Crash

**Expected behavior**
The program should make a directory and download episodes

**Info**
```
Name: anipy-cli
Version: 2.4.29
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: c:\python310\lib\site-packages
Requires: better-ffmpeg-progress, bs4, kitsu.py-extended, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, requests, tqdm
Required-by:
```

**Platform**
 - OS: Windows 10

**Additional context**
Error Log
```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\anipy-cli.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\anipy_cli\run_anipy_cli.py", line 8, in main
    cli.main()
  File "C:\Python310\lib\site-packages\anipy_cli\cli.py", line 665, in main
    download_cli(args.quality, args.ffmpeg, args.no_kitsu)
  File "C:\Python310\lib\site-packages\anipy_cli\cli.py", line 128, in download_cli
    download(show_entry, ffmpeg).download()
  File "C:\Python310\lib\site-packages\anipy_cli\download.py", line 55, in download
    self.show_folder.mkdir(exist_ok=True)
  File "C:\Python310\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\Videos\\Anime\\\nIsekai Ojisan\n'
```

**Comment by Dabbing-Guy** [comment]
Bruh. Newlines in the folder path 💀

**Comment by sdaqo** [comment]
> Bruh. Newlines in the folder path 💀

Gogo mods on it again
