### ISSUE TITLE
Failed to start anipy-cli

### ISSUE THREAD

**Issue by amazoedu0** [sdaqo/anipy-cli#82]
**Describe the bug**
Whenever I start anipy-cli errors are generated. I have tried to reinstall python and anipy-cli but nothing changes.

**Expected behavior**
Expected anipy-cli to start properly as before

**Info**
Name: anipy-cli
Version: 2.5.2
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: c:\users\pc planet\appdata\local\programs\python\python310\lib\site-packages
Requires: better-ffmpeg-progress, pypresence, python-dateutil, tqdm, bs4, requests, pycryptodomex, kitsu.py-extended, m3u8, moviepy
Required-by:

**Platform**
 - OS: Windows

**Additional context**
the error generated is shown below:

Traceback (most recent call last):
  File "C:\Users\Pc Planet\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pc Planet\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pc Planet\AppData\Local\Programs\Python\Python310\Scripts\anipy-cli.exe\__main__.py", line 4, in <module>
  File "C:\Users\Pc Planet\AppData\Local\Programs\Python\Python310\lib\site-packages\anipy_cli\__init__.py", line 16, in <module>
    from .query import query
  File "C:\Users\Pc Planet\AppData\Local\Programs\Python\Python310\lib\site-packages\anipy_cli\query.py", line 9, in <module>
    base_url = Config().gogoanime_url
  File "C:\Users\Pc Planet\AppData\Local\Programs\Python\Python310\lib\site-packages\anipy_cli\config.py", line 12, in __init__
    self._config_file = self._get_config_path() / "config.yaml"
  File "C:\Users\Pc Planet\AppData\Local\Programs\Python\Python310\lib\site-packages\anipy_cli\config.py", line 131, in _get_config_path
    raise SysNotFoundError(platform)
anipy_cli.config.SysNotFoundError: win32

**Comment by sdaqo** [comment]
I know why this occurs, wait a Minute.

**Comment by sdaqo** [comment]
Sorry for the inconvenience, to install the fixed version run `python3 -m pip install anipy-cli --upgrade` .

**Comment by amazoedu0** [comment]
I have tried this but it still gives the same error. 
This issue is only on `Windows`. On `Linux OS` it works fine. 
Kindly resolve this issue as `anipy-cli` is the only best cli app that is available to stream and download anime.

**Comment by amazoedu0** [comment]
It works now. 
Thanks a lot.
`anipy-cli` is the only best cli app that is available to stream and download `anime`.
