### ISSUE TITLE
Downloading anime bug

### ISSUE THREAD

**Issue by owleyz** [sdaqo/anipy-cli#84]
**Describe the bug**
okey so there is apparently bug with some aes implementation, when i tried to download Hyouka anime for example i got this... 

**To Reproduce**
Search: Hyouka
[1]
Hyouka

[2]
Hyouka (Dub)

[3]
Hyouka: Motsubeki Mono wa

[4]
Kyoshin to Hyouka no Shiro

[5]
Hyouka: Motsubeki Mono wa (Dub)

Enter Number: 1
Episode [1-22]: 5
Traceback (most recent call last):
  File "/home/hayo/.local/bin/anipy-cli", line 8, in <module>
    sys.exit(main())
  File "/home/hayo/.local/lib/python3.8/site-packages/anipy_cli/run_anipy_cli.py", line 7, in main
    cli.main()
  File "/home/hayo/.local/lib/python3.8/site-packages/anipy_cli/cli.py", line 509, in main
    default_cli(args.quality)
  File "/home/hayo/.local/lib/python3.8/site-packages/anipy_cli/cli.py", line 41, in default_cli
    url_class.stream_url()
  File "/home/hayo/.local/lib/python3.8/site-packages/anipy_cli/url_handler.py", line 237, in stream_url
    enc_id = self.aes_encrypt(id, self.key).decode()
  File "/home/hayo/.local/lib/python3.8/site-packages/anipy_cli/url_handler.py", line 208, in aes_encrypt
    AES.new(key, self.mode, iv=self.iv).encrypt(
  File "/home/hayo/.local/lib/python3.8/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/home/hayo/.local/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/home/hayo/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 287, in _create_cbc_cipher
    raise ValueError("Incorrect IV length (it must be %d bytes long)" %
ValueError: Incorrect IV length (it must be 16 bytes long)

**Info**
Name: anipy-cli
Version: 2.2.12
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /home/hayo/.local/lib/python3.8/site-packages
Requires: bs4, pycryptodomex, better-ffmpeg-progress, requests, tqdm
Required-by:

**Platform**
 - OS:  windows 10
 - hypervisor: WSL2

**Comment by Dabbing-Guy** [comment]
According to your Info, your 'anipy-cli' is very out of date. You should try running 'python3 -m pip install --upgrade anipy-cli' to update it and then try again.

**Comment by Dabbing-Guy** [comment]
And also you are using Python 3.8. The minimum version required for this project is 3.9

**Comment by owleyz** [comment]
Cool tnx, it werkz!!
