### ISSUE TITLE
Downloading anime bug (Some Anime have a whitespace at the end of the name)

### ISSUE THREAD

**Issue by jeromealapad13** [sdaqo/anipy-cli#85]
**Describe the bug**
Bug where the download path is not found because of the whitespace after the folder name (seen with "Neon Genesis Evangelion ")

**To Reproduce**
(dl) PS C:\Users\jerom> anipy-cli -d
***Download Mode***
Downloads are stored in: E:\ANIME
Search Kitsu for anime in Season? (y|n): 
n
Search: neon genesis eva
Add another search: (y|n) 
n

Current:  neon genesis eva
[1] Neon Genesis Evangelion
[2] Neon Genesis Evangelion (Dub)
[3] Neon Genesis Evangelion: Death & Rebirth
[4] Neon Genesis Evangelion: Death & Rebirth (Dub)
[5] Neon Genesis Evangelion: The End of Evangelion (Dub)
Enter Number: 1
Episode (Range with '-') [1-26]
1
anipy-cli: error: quality not avalible, using default
Neon Genesis Evangelion _1.mp4
E:\ANIME\Neon Genesis Evangelion \Neon Genesis Evangelion _1.mp4

Downloading: Neon Genesis Evangelion  EP: 1 - hls
Type: m3u8
Downloader: internal
Traceback (most recent call last):
  File "C:\Users\jerom\miniconda3\envs\dl\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jerom\miniconda3\envs\dl\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jerom\miniconda3\envs\dl\Scripts\anipy-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\jerom\miniconda3\envs\dl\lib\site-packages\anipy_cli\run_anipy_cli.py", line 8, in main
    cli.main()
  File "C:\Users\jerom\miniconda3\envs\dl\lib\site-packages\anipy_cli\cli.py", line 670, in main
    download_cli(args.
quality, args.ffmpeg, args.no_kitsu)
  File "C:\Users\jerom\miniconda3\envs\dl\lib\site-packages\anipy_cli\cli.py", line 133, in download_cli
    download(show_entry, ffmpeg).download()
  File "C:\Users\jerom\miniconda3\envs\dl\lib\site-packages\anipy_cli\download.py", line 85, in download
    self.multithread_m3u8_dl()
  File "C:\Users\jerom\miniconda3\envs\dl\lib\site-packages\anipy_cli\download.py", line 265, in multithread_m3u8_dl
    self.temp_folder.mkdir(exist_ok=True)
  File "C:\Users\jerom\miniconda3\envs\dl\lib\pathlib.py", line 1313, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\ANIME\\Neon Genesis Evangelion \\1_temp'

**Expected behavior**
Download the Episode

**Info**
Name: anipy-cli
Version: 2.5.3
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: c:\users\jerom\miniconda3\envs\dl\lib\site-packages
Requires: better-ffmpeg-progress, bs4, kitsu.py-extended, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, requests, tqdm
Required-by:

**Platform**
 - OS: Win11
 -  Python 3.9.6

**Additional context**
I made a temporary fix on my end at download.py where the show_name checks if the anime name has the character " " at the end and remove it if it exists.
![temp_flix](https://user-images.githubusercontent.com/58656012/192985097-262130d8-9c73-485a-9301-0a3118188a1f.png)

**Comment by Dabbing-Guy** [comment]
Thanks for finding out why the bug happened. I'll make a pull request to fix this. The better solution would be to just use the .strip() string method to get rid of the white space, instead of manually looking for it.

**Comment by jeromealapad13** [comment]
Thank you! ^^
